COMPILER = /usr/bin/clang++
CFLAGS = -g
MODE = release

foo: foo.cc
	$(COMPILER) foo.cc $(shell pkg-config --libs --cflags --static ../seastar/build/$(MODE)/seastar.pc) $(CFLAGS) -o foo

app: /opt/seastar/build/$(MODE)/libseastar.a app.cc
	$(COMPILER) app.cc $(shell pkg-config --libs --cflags --static /opt/seastar/build/$(MODE)/seastar.pc) $(CFLAGS) -o app

/opt/seastar/build/$(MODE)/libseastar.a:
	cd /opt/seastar && ./configure.py --mode="$(MODE)" --disable-dpdk --disable-hwloc --cflags="$(CFLAGS)" --compiler="$(COMPILER)"
	ninja -C /opt/seastar/build/$(MODE) libseastar.a
